/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getCurrentUser } from '../fn/operations/get-current-user';
import { GetCurrentUser$Params } from '../fn/operations/get-current-user';
import { login } from '../fn/operations/login';
import { Login$Params } from '../fn/operations/login';
import { logout } from '../fn/operations/logout';
import { Logout$Params } from '../fn/operations/logout';
import { refresh } from '../fn/operations/refresh';
import { Refresh$Params } from '../fn/operations/refresh';
import { register } from '../fn/operations/register';
import { Register$Params } from '../fn/operations/register';
import { TokenPair } from '../models/token-pair';
import { User } from '../models/user';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `register()` */
  static readonly RegisterPath = '/auth/register';

  /**
   * Register a new Org and its first User (as Admin).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `register()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register$Response(params: Register$Params, context?: HttpContext): Promise<StrictHttpResponse<TokenPair>> {
    const obs = register(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Register a new Org and its first User (as Admin).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `register$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register(params: Register$Params, context?: HttpContext): Promise<TokenPair> {
    const resp = this.register$Response(params, context);
    return resp.then((r: StrictHttpResponse<TokenPair>): TokenPair => r.body);
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = '/auth/login';

  /**
   * Exchange email + password for a token pair.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(params: Login$Params, context?: HttpContext): Promise<StrictHttpResponse<TokenPair>> {
    const obs = login(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Exchange email + password for a token pair.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(params: Login$Params, context?: HttpContext): Promise<TokenPair> {
    const resp = this.login$Response(params, context);
    return resp.then((r: StrictHttpResponse<TokenPair>): TokenPair => r.body);
  }

  /** Path part for operation `refresh()` */
  static readonly RefreshPath = '/auth/refresh';

  /**
   * Rotate a refresh token for a new token pair.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `refresh()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refresh$Response(params: Refresh$Params, context?: HttpContext): Promise<StrictHttpResponse<TokenPair>> {
    const obs = refresh(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Rotate a refresh token for a new token pair.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `refresh$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refresh(params: Refresh$Params, context?: HttpContext): Promise<TokenPair> {
    const resp = this.refresh$Response(params, context);
    return resp.then((r: StrictHttpResponse<TokenPair>): TokenPair => r.body);
  }

  /** Path part for operation `logout()` */
  static readonly LogoutPath = '/auth/logout';

  /**
   * Revoke a refresh token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `logout()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  logout$Response(params: Logout$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = logout(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Revoke a refresh token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `logout$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  logout(params: Logout$Params, context?: HttpContext): Promise<void> {
    const resp = this.logout$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `getCurrentUser()` */
  static readonly GetCurrentUserPath = '/auth/me';

  /**
   * The user identified by the bearer access token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUser$Response(params?: GetCurrentUser$Params, context?: HttpContext): Promise<StrictHttpResponse<User>> {
    const obs = getCurrentUser(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * The user identified by the bearer access token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUser(params?: GetCurrentUser$Params, context?: HttpContext): Promise<User> {
    const resp = this.getCurrentUser$Response(params, context);
    return resp.then((r: StrictHttpResponse<User>): User => r.body);
  }

}
