/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface User {
  email: string;
  id: string;
  orgId: string;
  role: Role;
}
