/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentShare {
  createdAt: string;
  documentId: string;
  grantedByUserId: string;
  grantedToUserId: string;
  id: string;
}
