/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Visibility } from '../models/visibility';
export interface Document {
  contentType: string;
  createdAt: string;
  fileName: string;
  folderId: string | null;
  id: string;
  ownerUserId: string;

  /**
   * Present only when visibility is PublicLink.
   */
  publicLinkToken?: string | null;
  sizeBytes: number;
  updatedAt: string;
  visibility: Visibility;
}
