/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Document } from '../models/document';
import { Folder } from '../models/folder';
export interface FolderChildren {
  documents: Array<Document>;
  folders: Array<Folder>;
}
