/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Folder {
  createdAt: string;
  id: string;
  name: string;
  ownerUserId: string;
  parentFolderId: string | null;
  updatedAt: string;
}
