/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Private: owner plus explicit share grants only. Organization: any authenticated user in the owner's org, discoverable. PublicLink: reachable only via publicLinkToken through the unauthenticated /public/documents/{token}/content route -- never listed for other users. Independent of explicit per-user share grants, which apply under any visibility.
 */
export type Visibility = 'Private' | 'Organization' | 'PublicLink';

