/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Visibility } from './visibility';

/**
 * Each possible value of `Visibility`
 */
export const VISIBILITY: Visibility[] = [
  'Private',
  'Organization',
  'PublicLink'
];