/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createFolder } from '../fn/operations/create-folder';
import { CreateFolder$Params } from '../fn/operations/create-folder';
import { deleteDocument } from '../fn/operations/delete-document';
import { DeleteDocument$Params } from '../fn/operations/delete-document';
import { deleteFolder } from '../fn/operations/delete-folder';
import { DeleteFolder$Params } from '../fn/operations/delete-folder';
import { Document } from '../models/document';
import { DocumentShare } from '../models/document-share';
import { downloadDocumentContent } from '../fn/operations/download-document-content';
import { DownloadDocumentContent$Params } from '../fn/operations/download-document-content';
import { downloadPublicDocumentContent } from '../fn/operations/download-public-document-content';
import { DownloadPublicDocumentContent$Params } from '../fn/operations/download-public-document-content';
import { Folder } from '../models/folder';
import { FolderChildren } from '../models/folder-children';
import { getDocument } from '../fn/operations/get-document';
import { GetDocument$Params } from '../fn/operations/get-document';
import { getFolder } from '../fn/operations/get-folder';
import { GetFolder$Params } from '../fn/operations/get-folder';
import { listDocuments } from '../fn/operations/list-documents';
import { ListDocuments$Params } from '../fn/operations/list-documents';
import { listDocumentShares } from '../fn/operations/list-document-shares';
import { ListDocumentShares$Params } from '../fn/operations/list-document-shares';
import { listFolderChildren } from '../fn/operations/list-folder-children';
import { ListFolderChildren$Params } from '../fn/operations/list-folder-children';
import { listFolders } from '../fn/operations/list-folders';
import { ListFolders$Params } from '../fn/operations/list-folders';
import { replaceDocumentContent } from '../fn/operations/replace-document-content';
import { ReplaceDocumentContent$Params } from '../fn/operations/replace-document-content';
import { revokeDocumentShare } from '../fn/operations/revoke-document-share';
import { RevokeDocumentShare$Params } from '../fn/operations/revoke-document-share';
import { setDocumentVisibility } from '../fn/operations/set-document-visibility';
import { SetDocumentVisibility$Params } from '../fn/operations/set-document-visibility';
import { shareDocumentWithUser } from '../fn/operations/share-document-with-user';
import { ShareDocumentWithUser$Params } from '../fn/operations/share-document-with-user';
import { updateDocument } from '../fn/operations/update-document';
import { UpdateDocument$Params } from '../fn/operations/update-document';
import { updateFolder } from '../fn/operations/update-folder';
import { UpdateFolder$Params } from '../fn/operations/update-folder';
import { uploadDocument } from '../fn/operations/upload-document';
import { UploadDocument$Params } from '../fn/operations/upload-document';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listDocuments()` */
  static readonly ListDocumentsPath = '/documents';

  /**
   * List documents visible to the caller, optionally scoped to a folder.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listDocuments()` instead.
   *
   * This method doesn't expect any request body.
   */
  listDocuments$Response(params?: ListDocuments$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Document>>> {
    const obs = listDocuments(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List documents visible to the caller, optionally scoped to a folder.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listDocuments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listDocuments(params?: ListDocuments$Params, context?: HttpContext): Promise<Array<Document>> {
    const resp = this.listDocuments$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Document>>): Array<Document> => r.body);
  }

  /** Path part for operation `uploadDocument()` */
  static readonly UploadDocumentPath = '/documents';

  /**
   * Upload a new document, owned by the caller.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadDocument()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadDocument$Response(params: UploadDocument$Params, context?: HttpContext): Promise<StrictHttpResponse<Document>> {
    const obs = uploadDocument(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Upload a new document, owned by the caller.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadDocument$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadDocument(params: UploadDocument$Params, context?: HttpContext): Promise<Document> {
    const resp = this.uploadDocument$Response(params, context);
    return resp.then((r: StrictHttpResponse<Document>): Document => r.body);
  }

  /** Path part for operation `getDocument()` */
  static readonly GetDocumentPath = '/documents/{id}';

  /**
   * Fetch a document's metadata.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDocument()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocument$Response(params: GetDocument$Params, context?: HttpContext): Promise<StrictHttpResponse<Document>> {
    const obs = getDocument(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Fetch a document's metadata.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDocument$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocument(params: GetDocument$Params, context?: HttpContext): Promise<Document> {
    const resp = this.getDocument$Response(params, context);
    return resp.then((r: StrictHttpResponse<Document>): Document => r.body);
  }

  /** Path part for operation `deleteDocument()` */
  static readonly DeleteDocumentPath = '/documents/{id}';

  /**
   * Delete a document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteDocument()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDocument$Response(params: DeleteDocument$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteDocument(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete a document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteDocument$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDocument(params: DeleteDocument$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteDocument$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `updateDocument()` */
  static readonly UpdateDocumentPath = '/documents/{id}';

  /**
   * Rename and/or move a document. Content and visibility are updated via their own endpoints.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateDocument()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDocument$Response(params: UpdateDocument$Params, context?: HttpContext): Promise<StrictHttpResponse<Document>> {
    const obs = updateDocument(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Rename and/or move a document. Content and visibility are updated via their own endpoints.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateDocument$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDocument(params: UpdateDocument$Params, context?: HttpContext): Promise<Document> {
    const resp = this.updateDocument$Response(params, context);
    return resp.then((r: StrictHttpResponse<Document>): Document => r.body);
  }

  /** Path part for operation `downloadDocumentContent()` */
  static readonly DownloadDocumentContentPath = '/documents/{id}/content';

  /**
   * Download a document's raw bytes.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadDocumentContent()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadDocumentContent$Response(params: DownloadDocumentContent$Params, context?: HttpContext): Promise<StrictHttpResponse<Blob>> {
    const obs = downloadDocumentContent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Download a document's raw bytes.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadDocumentContent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadDocumentContent(params: DownloadDocumentContent$Params, context?: HttpContext): Promise<Blob> {
    const resp = this.downloadDocumentContent$Response(params, context);
    return resp.then((r: StrictHttpResponse<Blob>): Blob => r.body);
  }

  /** Path part for operation `replaceDocumentContent()` */
  static readonly ReplaceDocumentContentPath = '/documents/{id}/content';

  /**
   * Replace a document's file bytes, keeping the same id and sharing state.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `replaceDocumentContent()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  replaceDocumentContent$Response(params: ReplaceDocumentContent$Params, context?: HttpContext): Promise<StrictHttpResponse<Document>> {
    const obs = replaceDocumentContent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Replace a document's file bytes, keeping the same id and sharing state.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `replaceDocumentContent$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  replaceDocumentContent(params: ReplaceDocumentContent$Params, context?: HttpContext): Promise<Document> {
    const resp = this.replaceDocumentContent$Response(params, context);
    return resp.then((r: StrictHttpResponse<Document>): Document => r.body);
  }

  /** Path part for operation `setDocumentVisibility()` */
  static readonly SetDocumentVisibilityPath = '/documents/{id}/visibility';

  /**
   * Change who can find a document. Setting PublicLink (re)generates publicLinkToken; setting Private or Organization clears it. This is separate from per-user share grants, which persist regardless of visibility.
   * .
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setDocumentVisibility()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setDocumentVisibility$Response(params: SetDocumentVisibility$Params, context?: HttpContext): Promise<StrictHttpResponse<Document>> {
    const obs = setDocumentVisibility(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Change who can find a document. Setting PublicLink (re)generates publicLinkToken; setting Private or Organization clears it. This is separate from per-user share grants, which persist regardless of visibility.
   * .
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setDocumentVisibility$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setDocumentVisibility(params: SetDocumentVisibility$Params, context?: HttpContext): Promise<Document> {
    const resp = this.setDocumentVisibility$Response(params, context);
    return resp.then((r: StrictHttpResponse<Document>): Document => r.body);
  }

  /** Path part for operation `listDocumentShares()` */
  static readonly ListDocumentSharesPath = '/documents/{id}/shares';

  /**
   * List explicit per-user share grants for a document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listDocumentShares()` instead.
   *
   * This method doesn't expect any request body.
   */
  listDocumentShares$Response(params: ListDocumentShares$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<DocumentShare>>> {
    const obs = listDocumentShares(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List explicit per-user share grants for a document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listDocumentShares$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listDocumentShares(params: ListDocumentShares$Params, context?: HttpContext): Promise<Array<DocumentShare>> {
    const resp = this.listDocumentShares$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<DocumentShare>>): Array<DocumentShare> => r.body);
  }

  /** Path part for operation `shareDocumentWithUser()` */
  static readonly ShareDocumentWithUserPath = '/documents/{id}/shares';

  /**
   * Grant a specific user access to a document, regardless of its visibility.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `shareDocumentWithUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  shareDocumentWithUser$Response(params: ShareDocumentWithUser$Params, context?: HttpContext): Promise<StrictHttpResponse<DocumentShare>> {
    const obs = shareDocumentWithUser(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Grant a specific user access to a document, regardless of its visibility.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `shareDocumentWithUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  shareDocumentWithUser(params: ShareDocumentWithUser$Params, context?: HttpContext): Promise<DocumentShare> {
    const resp = this.shareDocumentWithUser$Response(params, context);
    return resp.then((r: StrictHttpResponse<DocumentShare>): DocumentShare => r.body);
  }

  /** Path part for operation `revokeDocumentShare()` */
  static readonly RevokeDocumentSharePath = '/documents/{id}/shares/{userId}';

  /**
   * Revoke a specific user's share grant for a document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `revokeDocumentShare()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeDocumentShare$Response(params: RevokeDocumentShare$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = revokeDocumentShare(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Revoke a specific user's share grant for a document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `revokeDocumentShare$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeDocumentShare(params: RevokeDocumentShare$Params, context?: HttpContext): Promise<void> {
    const resp = this.revokeDocumentShare$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `downloadPublicDocumentContent()` */
  static readonly DownloadPublicDocumentContentPath = '/public/documents/{token}/content';

  /**
   * Download a document by its public-link token. Unauthenticated -- the only route in this contract that does not require a bearer token. Never appears in any user's file list or "shared with"; reachable only by someone holding the exact link.
   * .
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadPublicDocumentContent()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadPublicDocumentContent$Response(params?: DownloadPublicDocumentContent$Params, context?: HttpContext): Promise<StrictHttpResponse<Blob>> {
    const obs = downloadPublicDocumentContent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Download a document by its public-link token. Unauthenticated -- the only route in this contract that does not require a bearer token. Never appears in any user's file list or "shared with"; reachable only by someone holding the exact link.
   * .
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadPublicDocumentContent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadPublicDocumentContent(params?: DownloadPublicDocumentContent$Params, context?: HttpContext): Promise<Blob> {
    const resp = this.downloadPublicDocumentContent$Response(params, context);
    return resp.then((r: StrictHttpResponse<Blob>): Blob => r.body);
  }

  /** Path part for operation `listFolders()` */
  static readonly ListFoldersPath = '/folders';

  /**
   * List the caller's folders, optionally scoped to a parent.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listFolders()` instead.
   *
   * This method doesn't expect any request body.
   */
  listFolders$Response(params?: ListFolders$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Folder>>> {
    const obs = listFolders(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List the caller's folders, optionally scoped to a parent.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listFolders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listFolders(params?: ListFolders$Params, context?: HttpContext): Promise<Array<Folder>> {
    const resp = this.listFolders$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Folder>>): Array<Folder> => r.body);
  }

  /** Path part for operation `createFolder()` */
  static readonly CreateFolderPath = '/folders';

  /**
   * Create a virtual folder, owned by the caller.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createFolder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createFolder$Response(params: CreateFolder$Params, context?: HttpContext): Promise<StrictHttpResponse<Folder>> {
    const obs = createFolder(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create a virtual folder, owned by the caller.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createFolder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createFolder(params: CreateFolder$Params, context?: HttpContext): Promise<Folder> {
    const resp = this.createFolder$Response(params, context);
    return resp.then((r: StrictHttpResponse<Folder>): Folder => r.body);
  }

  /** Path part for operation `getFolder()` */
  static readonly GetFolderPath = '/folders/{id}';

  /**
   * Fetch a folder's metadata.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFolder()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFolder$Response(params: GetFolder$Params, context?: HttpContext): Promise<StrictHttpResponse<Folder>> {
    const obs = getFolder(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Fetch a folder's metadata.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFolder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFolder(params: GetFolder$Params, context?: HttpContext): Promise<Folder> {
    const resp = this.getFolder$Response(params, context);
    return resp.then((r: StrictHttpResponse<Folder>): Folder => r.body);
  }

  /** Path part for operation `deleteFolder()` */
  static readonly DeleteFolderPath = '/folders/{id}';

  /**
   * Delete an empty folder.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteFolder()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteFolder$Response(params: DeleteFolder$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteFolder(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete an empty folder.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteFolder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteFolder(params: DeleteFolder$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteFolder$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `updateFolder()` */
  static readonly UpdateFolderPath = '/folders/{id}';

  /**
   * Rename and/or move a folder.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateFolder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateFolder$Response(params: UpdateFolder$Params, context?: HttpContext): Promise<StrictHttpResponse<Folder>> {
    const obs = updateFolder(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Rename and/or move a folder.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateFolder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateFolder(params: UpdateFolder$Params, context?: HttpContext): Promise<Folder> {
    const resp = this.updateFolder$Response(params, context);
    return resp.then((r: StrictHttpResponse<Folder>): Folder => r.body);
  }

  /** Path part for operation `listFolderChildren()` */
  static readonly ListFolderChildrenPath = '/folders/{id}/children';

  /**
   * List the subfolders and documents directly inside a folder.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listFolderChildren()` instead.
   *
   * This method doesn't expect any request body.
   */
  listFolderChildren$Response(params: ListFolderChildren$Params, context?: HttpContext): Promise<StrictHttpResponse<FolderChildren>> {
    const obs = listFolderChildren(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List the subfolders and documents directly inside a folder.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listFolderChildren$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listFolderChildren(params: ListFolderChildren$Params, context?: HttpContext): Promise<FolderChildren> {
    const resp = this.listFolderChildren$Response(params, context);
    return resp.then((r: StrictHttpResponse<FolderChildren>): FolderChildren => r.body);
  }

}
