/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateFolderRequest } from '../../models/create-folder-request';
import { Folder } from '../../models/folder';

export interface CreateFolder$Params {
      body: CreateFolderRequest
}

export function createFolder(http: HttpClient, rootUrl: string, params: CreateFolder$Params, context?: HttpContext): Observable<StrictHttpResponse<Folder>> {
  const rb = new RequestBuilder(rootUrl, createFolder.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Folder>;
    })
  );
}

createFolder.PATH = '/folders';
