/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentShare } from '../../models/document-share';

export interface ListDocumentShares$Params {
  id: string;
}

export function listDocumentShares(http: HttpClient, rootUrl: string, params: ListDocumentShares$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentShare>>> {
  const rb = new RequestBuilder(rootUrl, listDocumentShares.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DocumentShare>>;
    })
  );
}

listDocumentShares.PATH = '/documents/{id}/shares';
