/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Document } from '../../models/document';

export interface ListDocuments$Params {
  folderId?: string;

/**
 * When true, restrict to documents owned by the caller.
 */
  mine?: boolean;
}

export function listDocuments(http: HttpClient, rootUrl: string, params?: ListDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Document>>> {
  const rb = new RequestBuilder(rootUrl, listDocuments.PATH, 'get');
  if (params) {
    rb.query('folderId', params.folderId, {});
    rb.query('mine', params.mine, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Document>>;
    })
  );
}

listDocuments.PATH = '/documents';
