/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FolderChildren } from '../../models/folder-children';

export interface ListFolderChildren$Params {
  id: string;
}

export function listFolderChildren(http: HttpClient, rootUrl: string, params: ListFolderChildren$Params, context?: HttpContext): Observable<StrictHttpResponse<FolderChildren>> {
  const rb = new RequestBuilder(rootUrl, listFolderChildren.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FolderChildren>;
    })
  );
}

listFolderChildren.PATH = '/folders/{id}/children';
