/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Folder } from '../../models/folder';
import { UpdateFolderRequest } from '../../models/update-folder-request';

export interface UpdateFolder$Params {
  id: string;
      body: UpdateFolderRequest
}

export function updateFolder(http: HttpClient, rootUrl: string, params: UpdateFolder$Params, context?: HttpContext): Observable<StrictHttpResponse<Folder>> {
  const rb = new RequestBuilder(rootUrl, updateFolder.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Folder>;
    })
  );
}

updateFolder.PATH = '/folders/{id}';
